In [ ]:
#Write statement to import numpy
# Q:1 TO import numpy we install numpy using !pip install numpy after this we we can use numpy using the import numpy as np.
#numpy is a open source library.

In [1]:
# Q:2 Create an array using numpy ?
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
## Q :3 Create an array of 10 random integers ?

import numpy as np
np.random.randint(1,20 ,10)

array([ 3,  2, 19,  6, 17,  2, 16, 17, 11,  1])

In [3]:
##Q.4 = Create an array of elements from 10-20?
import numpy as np
a=np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
#Q.5 = Create an array which contains value 8 , 10 times ?
import numpy as np
a=np.ones(10)*8
a

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [5]:
#Q.6 = Create a one dimensional array and convert that into 4*3 matrix ?
import numpy as np
a=np.arange(1,13)
a
#FOR conversion
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
#Q.7 = Create a 2D array of size 3*3 but all the elements should be between 0 to 1 ?
import numpy as np
a=np.random.rand(3,3)
a

array([[0.97475109, 0.40825631, 0.19726517],
       [0.55354783, 0.79477327, 0.96052716],
       [0.9440016 , 0.6216709 , 0.06657787]])

In [8]:
#Q.8 = Conatenate 2D array horizontally and vertically ?
import numpy as np
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [10]:

##Q.11 What is view vs copy ? explain it with example ? 
#view ---->#view method mean modification in original array
import numpy as np
a =np.array([1,2,3,4,5,5,6,75,8]) 
b =a[2:5]
b[:]=0
b
a

array([ 1,  2,  3,  0,  0,  5,  6, 75,  8])

In [12]:
#copy --->#copy method will not update youe original array
a =np.array([1,2,3,4,5,6,6,76,8]) 
b =a[1:5].copy()
b[:]=0
b
a

array([ 1,  2,  3,  4,  5,  6,  6, 76,  8])

In [20]:
#hstack -->hstack is horizontol one dimensional array
#vstack ---> vstack is vertical two dimensional array
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
np.hstack([a,b,c])



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#Q.9 difference between zeros() , ones() , eye() , diag() , linspace() , unique() , random(randint() , rand()) with example.


In [21]:
a=np.array([1,2,3,4,5])
np.zeros

<function numpy.zeros>

In [22]:
a=np.array([1,2,3,4,5])
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [27]:
a=np.array([1,2,3,4,5])
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])